# Generated by Django 2.2.9 on 2020-02-15 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capacity',
            old_name='value',
            new_name='capacity_value',
        ),
        migrations.RenameField(
            model_name='capital',
            old_name='value',
            new_name='capital_value',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='value',
            new_name='demand_value',
        ),
        migrations.RenameField(
            model_name='opex',
            old_name='value',
            new_name='opex_value',
        ),
    ]
