# Generated by Django 2.2.9 on 2020-02-21 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_capacity_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('util_value', models.FloatField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Option')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Year')),
            ],
        ),
    ]
